apiVersion: v1
kind: Namespace
metadata:
  name: ambassador
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ambassador-healthcheck
  namespace: ambassador
spec:
  healthCheck:
    type: HTTP
    requestPath: /ambassador/v0/check_ready
    port: 8877
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3